[package]
name = "iced_form"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git="https://github.com/iced-rs/iced", features = ["advanced"] }

[dev-dependencies]
derive_builder = "0.20.0"
